'use strict';

const fs   = require('fs');
const path = require('path');

function truncate(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}

function generateTriageReport(channel, triageResult, projectRoot) {
  const root = projectRoot || process.cwd();
  const now = new Date();
  const ts = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const tsDisplay = now.toISOString();

  const accepted = triageResult.accepted || [];
  const declined = triageResult.declined || [];
  const unclear  = triageResult.unclear  || [];
  const total = accepted.length + declined.length + unclear.length;

  const acceptedRows = accepted.map(({ ticket, request_id }) =>
    `| ${ticket.id || ticket._source_row} | ${truncate(ticket.title, 50)} | ${ticket._classified || '?'} | ${request_id} |`
  ).join('\n') || '| — | — | — | — |';

  const declinedRows = declined.map(({ ticket, reason }) =>
    `| ${ticket.id || ticket._source_row} | ${truncate(ticket.title, 50)} | ${truncate(reason, 60)} |`
  ).join('\n') || '| — | — | — |';

  const unclearRows = unclear.map(({ ticket }) =>
    `| ${ticket.id || ticket._source_row} | ${truncate(ticket.title, 50)} |`
  ).join('\n') || '| — | — |';

  const pkgVersion = (() => {
    try {
      return require(path.join(root, 'package.json')).version;
    } catch {
      return 'unknown';
    }
  })();

  const report = `# Triage Report — ${channel.name}

**Session**: ${tsDisplay}
**Channel**: ${channel.name} (${channel.type})
**Total Tickets**: ${total}

## Summary

| Decision | Count |
|----------|-------|
| Accepted | ${accepted.length} |
| Declined | ${declined.length} |
| Unclear  | ${unclear.length} |

## Accepted Tickets

| Source ID | Title | Type | Request Created |
|-----------|-------|------|-----------------|
${acceptedRows}

## Declined Tickets

| Source ID | Title | Reason |
|-----------|-------|--------|
${declinedRows}

## Unclear Tickets (not actioned)

| Source ID | Title |
|-----------|-------|
${unclearRows}

---
*Generated by ViePilot vp-intake v${pkgVersion}*
`;

  const intakeDir = path.join(root, '.viepilot', 'intake');
  if (!fs.existsSync(intakeDir)) {
    fs.mkdirSync(intakeDir, { recursive: true });
  }

  const reportPath = path.join(intakeDir, `TRIAGE-${ts}.md`);
  fs.writeFileSync(reportPath, report, 'utf8');
  return reportPath;
}

module.exports = { generateTriageReport };
